name = "sprakmonsterlabbet"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV for magic link tokens
[[kv_namespaces]]
binding = "KV"
id = "a507970ece464c57be2f38b537041f70"

# Hemligheter sätts via: npx wrangler secret put NAMN
# RESEND_API_KEY
# SESSION_SECRET
# ANTHROPIC_API_KEY

[assets]
directory = "./pages"

[triggers]
crons = ["0 3 1 * *"]

[[d1_databases]]
binding = "SML_DB"
database_name = "sprakmonsterlabbet"
database_id = "e95682e7-93e4-40e9-a41f-1ddc1ad34cd3"
